# Page settings
title = "podcast"
theme = "internet-weblog"
BaseURL = "http://localhost:1313/podcast/"
languageCode = "en-us"
Paginate = 10
SectionPagesMenu = "main"

  
[author]
	Handle = "DV"
	FirstName = "DV"
	LastName = ""
	AboutPage = "/podcast/about"
	Location = "Tbilisi, GE"
    
[params]
    RSSEnabled = true
    RSSSections = [ "Posts" ]
    Description = "podcast description"
    ShowCopyright = true
    
[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"
    
[[menu.main]]
	name = "Posts"
	weight = 1
	identifier = "posts"
	url = "/posts/"