# Page settings
title = "ეს"
theme = "anybodyhome"
BaseURL = "https://kasradzenika.github.io/podcast.ge_build/"
LanguageCode = "ka-GE"
Paginate = 5
SectionPagesMenu = "main"
GoogleAnalytics = "UA-69266857-2"
DisqusShortname = "podcasterge"

[author]
	Handle = "Deep Vigilant"
	FirstName = "ნიკა"
	LastName = "კასრაძე"
	AboutPage = "mailto:kasradzenika@yahoo.com"
	Location = "Tbilisi, GE"
    
[params]
    Description = "არა-მეინსტრიმული ისტორიები"
    RSSEnabled = true
    ShowCopyright = true
    
[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"
    
[[menu.main]]
	name = "პოსტები"
	weight = 1
	identifier = "posts"
	url = "/posts/"
