# Page settings
title = "რაღაცნაირი"
# theme = "anybodyhome"
BaseURL = "https://podcast.ge/"
LanguageCode = "ka-GE"
Paginate = 5
SectionPagesMenu = "main"
GoogleAnalytics = "UA-69266857-2"
DisqusShortname = "podcasterge"
  
[author]
	Handle = "Deep Vigil"
	FirstName = "ნიკა"
	LastName = "კასრაძე"
	AboutPage = "https://fb.com/DeepVigilant"
	Location = "Tbilisi, GE"
    
[params]
    Description = "წარმატების ისტორიები"
    RSSEnabled = true
    ShowCopyright = true
    
[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"
    
[[menu.main]]
	name = "პოსტები"
	weight = 1
	identifier = "posts"
	url = "/posts/"
