# Page settings
title = "პოდკასტი"
theme = "internet-weblog"
BaseURL = "https://kasradzenika.github.io/podcast/"
LanguageCode = "ka-GE"
Paginate = 10
SectionPagesMenu = "main"
GoogleAnalytics = "UA-69266857-2"
DisqusShortname = "podcasterge"
  
[author]
	Handle = "კვარკი"
	FirstName = "ნიკა"
	LastName = "კასრაძე"
	AboutPage = "/podcast/about/"
	Location = "Tbilisi, GE"
    
[params]
    Description = "წარმატების ისტორიები"
    RSSEnabled = true
    ShowCopyright = true
    
[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"
    
[[menu.main]]
	name = "პოსტები"
	weight = 1
	identifier = "posts"
	url = "/posts/"
