# Page settings
title = "podcast"
theme = "internet-weblog"
BaseURL = "https://kasradzenika.github.io/podcast/"
LanguageCode = "en-us"
Paginate = 10
SectionPagesMenu = "main"
GoogleAnalytics = "UA-69266857-2"
DisqusShortname = "podcasterge"
  
[author]
	Handle = "Nika"
	FirstName = "Nika"
	LastName = ""
	AboutPage = "/podcast/about/"
	Location = "Tbilisi, GE"
    
[params]
    RSSEnabled = true
    Description = "podcast description"
    ShowCopyright = true
    
[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"
    
[[menu.main]]
	name = "Posts"
	weight = 1
	identifier = "posts"
	url = "/posts/"